version: "3.3"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: ms-rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  postgres:
    container_name: ms-postgres-container
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./data:/data/db
    ports:
      - "5432:5432"

  email:
    build:
      context: .
      dockerfile: docker/email
    container_name: ms-email-container
    restart: always
    env_file: ./email/.env
    depends_on:
      - postgres

  event:
    build:
      context: .
      dockerfile: docker/event
    container_name: ms-event-container
    restart: always
    ports:
      - "8080:8080"
    env_file: ./event/.env
    depends_on:
      - postgres

  payment:
    build:
      context: .
      dockerfile: docker/payment
    container_name: ms-payment-container
    restart: always
    ports:
      - "8081:8081"
    env_file: ./payment/.env
    depends_on:
      - postgres

  user:
    build:
      context: .
      dockerfile: docker/user
    container_name: ms-user-container
    restart: always
    ports:
      - "8082:8082"
    env_file: ./user/.env
    depends_on:
      - postgres
